[package]
name = "day_6"
version = "0.1.0"
authors = ["Bruno Roy <brusi_roy@hotmail.com>"]

[[bin]]
name = "puzzle_1"
path = "src/puzzle_1.rs"

[[bin]]
name = "puzzle_2"
path = "src/puzzle_2.rs"

[dependencies]
